x-logging: &default-logging
  logging:
    driver: json-file
    options: { max-size: "10m", max-file: "3" }

services:
  app:
    build:
      context: .
      args:
        BUILD_ENV: ${ENV:-development}
    env_file:
      - .env.dev
    volumes:
      - .:/code
    command: uvicorn src.web.app:app --host 0.0.0.0 --port 8000 --reload --no-access-log

  celery-worker:
    build:
      context: .
      args:
        BUILD_ENV: ${ENV:-development}
    env_file:
      - .env.dev
    volumes:
      - .:/code
  celery-beat:
    build:
      context: .
      args:
        BUILD_ENV: ${ENV:-development}
    env_file:
      - .env.dev
    volumes:
      - .:/code
  flower:
    <<: *default-logging
    build:
      context: .
      args:
        BUILD_ENV: ${ENV:-development}
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A src.scheduler.app_celery flower --port=5555
    ports:
      - ${EXPOSE_FLOWER_PORT:-5555}:5555
    env_file:
      - .env.dev
    environment:
      APP_SERVICE_NAME: flower
    volumes:
      - .:/code
  postgres:
    ports:
      - ${EXPOSE_DATABASE_PORT:-5432}:5432
  redis:
    ports:
      - ${EXPOSE_REDIS_PORT:-6379}:6379
