"""add_user_and_notify_schema

Revision ID: 786c1cfcb40a
Revises: 6539cd8019da
Create Date: 2025-10-29 08:12:22.870995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '786c1cfcb40a'
down_revision: Union[str, Sequence[str], None] = '6539cd8019da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tg_users_pkey'))
    )
    op.create_index(op.f('ix_tg_users_is_active'), 'tg_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_tg_users_tg_chat_id'), 'tg_users', ['tg_chat_id'], unique=False)
    op.create_index(op.f('ix_tg_users_tg_user_id'), 'tg_users', ['tg_user_id'], unique=True)
    op.create_index(op.f('ix_tg_users_username'), 'tg_users', ['username'], unique=False)
    op.create_table('filters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tg_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tg_user_id'], ['tg_users.id'], name=op.f('filters_tg_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('filters_pkey'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filter_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('min_interval_sec', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('telegram')", name=op.f('subscriptions_ck_subs_channel_check')),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], name=op.f('subscriptions_filter_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey')),
    sa.UniqueConstraint('filter_id', 'channel', 'chat_id', name=op.f('subscriptions_filter_id_channel_chat_id_key'))
    )
    op.create_index(op.f('ix_subscriptions_filter_id'), 'subscriptions', ['filter_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_active'), 'subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_last_sent_at'), 'subscriptions', ['last_sent_at'], unique=False)
    op.create_index(op.f('ix_listing_photos_listing_id'), 'listing_photos', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_photos_listing_id'), table_name='listing_photos')
    op.drop_index(op.f('ix_subscriptions_last_sent_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_active'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_filter_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('filters')
    op.drop_index(op.f('ix_tg_users_username'), table_name='tg_users')
    op.drop_index(op.f('ix_tg_users_tg_user_id'), table_name='tg_users')
    op.drop_index(op.f('ix_tg_users_tg_chat_id'), table_name='tg_users')
    op.drop_index(op.f('ix_tg_users_is_active'), table_name='tg_users')
    op.drop_table('tg_users')
    # ### end Alembic commands ###
