"""update_tg_users_table

Revision ID: 220ff9d3bd35
Revises: 786c1cfcb40a
Create Date: 2025-10-30 08:28:26.227423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220ff9d3bd35'
down_revision: Union[str, Sequence[str], None] = '786c1cfcb40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('is_premium', sa.Boolean(), nullable=False))
    op.add_column('tg_users', sa.Column('last_interaction', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tg_users_last_interaction'), 'tg_users', ['last_interaction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_users_last_interaction'), table_name='tg_users')
    op.drop_column('tg_users', 'last_interaction')
    op.drop_column('tg_users', 'is_premium')
    # ### end Alembic commands ###
