"""init_schema

Revision ID: 6539cd8019da
Revises: 
Create Date: 2025-10-28 19:46:24.777787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '6539cd8019da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('outbox_messages_pkey'))
    )
    op.create_index(op.f('ix_outbox_messages_aggregate_type'), 'outbox_messages', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_outbox_messages_created_at'), 'outbox_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_messages_message_type'), 'outbox_messages', ['message_type'], unique=False)
    op.create_table('sources',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('sources_pkey'))
    )
    op.create_table('listings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('price_amount', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(length=8), nullable=True),
    sa.Column('address_country', sa.String(length=64), nullable=True),
    sa.Column('address_state', sa.String(length=128), nullable=True),
    sa.Column('address_city', sa.String(length=128), nullable=True),
    sa.Column('address_district', sa.String(length=128), nullable=True),
    sa.Column('address_street', sa.String(length=256), nullable=True),
    sa.Column('address_building', sa.String(length=64), nullable=True),
    sa.Column('address_zip', sa.String(length=32), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_owner_id', sa.String(length=128), nullable=True),
    sa.Column('owner_name', sa.String(length=256), nullable=True),
    sa.Column('owner_type_declared', sa.String(length=32), nullable=True),
    sa.Column('owner_contacts', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('listing_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('listing_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_code'], ['sources.code'], name=op.f('listings_source_code_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('listings_pkey')),
    sa.UniqueConstraint('source_code', 'external_id', name='uq_listing_src_ext')
    )
    op.create_index('ix_listing_city_price', 'listings', ['address_city', 'price_amount'], unique=False)
    op.create_index('ix_listing_fingerprint_status', 'listings', ['fingerprint', 'status'], unique=False)
    op.create_index('ix_listing_status_updated', 'listings', ['status', 'updated_at'], unique=False)
    op.create_index(op.f('ix_listings_address_city'), 'listings', ['address_city'], unique=False)
    op.create_index(op.f('ix_listings_fingerprint'), 'listings', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_listings_first_seen_at'), 'listings', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_listings_last_seen_at'), 'listings', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_table('raw_listings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('fetch_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_code'], ['sources.code'], name=op.f('raw_listings_source_code_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_listings_pkey')),
    sa.UniqueConstraint('source_code', 'external_id', name='uq_raw_src_ext')
    )
    op.create_index(op.f('ix_raw_listings_fetched_at'), 'raw_listings', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_raw_listings_processing_status'), 'raw_listings', ['processing_status'], unique=False)
    op.create_index('ix_raw_status_fetched', 'raw_listings', ['processing_status', 'fetched_at'], unique=False)
    op.create_table('listing_photos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('listing_photos_listing_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('listing_photos_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_photos')
    op.drop_index('ix_raw_status_fetched', table_name='raw_listings')
    op.drop_index(op.f('ix_raw_listings_processing_status'), table_name='raw_listings')
    op.drop_index(op.f('ix_raw_listings_fetched_at'), table_name='raw_listings')
    op.drop_table('raw_listings')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_last_seen_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_first_seen_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_fingerprint'), table_name='listings')
    op.drop_index(op.f('ix_listings_address_city'), table_name='listings')
    op.drop_index('ix_listing_status_updated', table_name='listings')
    op.drop_index('ix_listing_fingerprint_status', table_name='listings')
    op.drop_index('ix_listing_city_price', table_name='listings')
    op.drop_index('idx_listings_location', table_name='listings', postgresql_using='gist')
    op.drop_table('listings')
    op.drop_table('sources')
    op.drop_index(op.f('ix_outbox_messages_message_type'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_created_at'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_aggregate_type'), table_name='outbox_messages')
    op.drop_table('outbox_messages')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS pgcrypto;")

