"""create_outbox_table

Revision ID: 9e03fd58b153
Revises: 7a2c83609cf5
Create Date: 2025-10-26 09:50:26.881909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e03fd58b153"
down_revision: Union[str, Sequence[str], None] = "7a2c83609cf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=True),
        sa.Column("message_type", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("outbox_messages_pkey")),
        sa.UniqueConstraint(
            "aggregate_type", "aggregate_id", "message_type", name="uq_outbox_agg_msg"
        ),
    )
    op.create_index(
        op.f("ix_outbox_messages_aggregate_id"),
        "outbox_messages",
        ["aggregate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_messages_aggregate_type"),
        "outbox_messages",
        ["aggregate_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_messages_created_at"),
        "outbox_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_messages_message_type"),
        "outbox_messages",
        ["message_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outbox_messages_message_type"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_created_at"), table_name="outbox_messages")
    op.drop_index(
        op.f("ix_outbox_messages_aggregate_type"), table_name="outbox_messages"
    )
    op.drop_index(op.f("ix_outbox_messages_aggregate_id"), table_name="outbox_messages")
    op.drop_table("outbox_messages")
    # ### end Alembic commands ###
