from typing import Protocol, Mapping, Any, Callable, AsyncIterable

from .types import Request, Response, Page
from ..domain.ingest import RawListing


class Policy(Protocol):
    async def send(self, req: Request, call_next: Callable) -> Response: ...


class AsyncHttpTransport(Protocol):
    async def send(self, req: Request) -> Response: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc, tb): ...


class AsyncClient(Protocol):
    async def send(self, req: "Request") -> "Response": ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc, tb): ...


class Provider(Protocol):
    async def search(
        self, filters: Mapping[str, Any] = None, cursor: str | int | None = None
    ) -> Page: ...
    async def iter(self, ids: list[str]) -> AsyncIterable[RawListing]: ...
